language: python
python:
    - "3.8"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    # add examples here and define which boards should be tested (only compile test)
    - PLATFORMIO_CI_SRC=examples/CustomI2C/CustomI2C.ino TESTBOARD=arduino_avr,arduino_arm,esp
    - PLATFORMIO_CI_SRC=examples/CustomSPI/CustomSPI.ino TESTBOARD=arduino_avr,arduino_arm,esp
    - PLATFORMIO_CI_SRC=examples/Hack/ChangeUID/ChangeUID.ino TESTBOARD=arduino_avr,arduino_arm,esp
    - PLATFORMIO_CI_SRC=examples/Hack/FixBrickedUID/FixBrickedUID.ino TESTBOARD=arduino_avr,arduino_arm,esp
    - PLATFORMIO_CI_SRC=examples/CheckFirmware/CheckFirmware.ino TESTBOARD=arduino_avr,arduino_arm,esp
    - PLATFORMIO_CI_SRC=examples/DumpInfo/DumpInfo.ino TESTBOARD=arduino_avr,arduino_arm,esp
    - PLATFORMIO_CI_SRC=examples/ReadUidMultiReader/ReadUidMultiReader.ino TESTBOARD=arduino_avr,arduino_arm,esp

install:
    - pip install -U platformio
    - platformio settings set enable_telemetry no # disable spy
    - platformio settings set strict_ssl yes # enable security

script:
    # short the string comparison
    - stringContain() { [ -z "${2##*$1*}" ]; }
    # selectable board tests @Rotzbua
    # prints only warnings and errors, to show all remove "1>/dev/null"
    - board="arduino_avr";  if stringContain "$board" "$TESTBOARD"; then echo "check board $board"; ouput=$(platformio ci --lib=. --board=uno --board=megaatmega1280) || exit $?; echo "--<Result>--"; echo "$ouput" | grep --no-messages --ignore-case -E "^(PLATFORM|HARDWARE|RAM|Flash|Device|Data|Program|text|[0-9])"; else echo "skip board test of $board"; fi
    - board="arduino_arm";  if stringContain "$board" "$TESTBOARD"; then echo "check board $board"; ouput=$(platformio ci --lib=. --board=due --board=zero) || exit $?; echo "--<Result>--"; echo "$ouput" | grep --no-messages --ignore-case -E "^(PLATFORM|HARDWARE|RAM|Flash|Device|Data|Program|text|[0-9])"; else echo "skip board test of $board"; fi
    - board="esp";  if stringContain "$board" "$TESTBOARD"; then echo "check board $board"; ouput=$(platformio ci --lib=. --board=d1_mini) || exit $?; echo "--<Result>--"; echo "$ouput" | grep --no-messages --ignore-case -E "^(PLATFORM|HARDWARE|RAM|Flash|Device|Data|Program|text|[0-9])"; else echo "skip board test of $board"; fi
    
